<?php
/**
 * Created by PhpStorm.
 * User: v_luyan
 * Date: 2019/7/15
 * Time: 15:20
 */

namespace app\lib\exception;

use Exception;
use think\exception\Handle;
use think\Log;

class ExceptionHandler extends Handle
{
    // 自定义错误码
    private $code;
    // 自定义异常信息
    private $msg;

    public function render(Exception $e)
    {
        //分别处理两种不容类型异常：1、用户错误 2.代码与运行时错误
        if ($e instanceof BaseException) {
            $this->code = $e->code;
            $this->msg = $e->msg;
        } else {
            //这里是在运行时产生的各种异常，所以无法准确输出异常信息，所以只能统一输出是服务器错误信息
            $this->code = 5000;
            $this->msg = "系统内部错误";
        }
        $result = [
            'code' => $this->code,
            'data'=>null,
            'msg' => $this->msg,
        ];
        //将异常写入日志
        Log::record("[".$this->code."]".$this->msg,'error');
        Log::record($e->getMessage(),'error');
        return json($result);

        //return parent::render($e); // TODO: Change the autogenerated stub
    }




}